apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k2m5jlwoi-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/k2m5jlwoi-java-quarkus-gitops