apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k2m5jlwoi-java-quarkus
  janus-idp.io/tekton: k2m5jlwoi-java-quarkus
  backstage.io/kubernetes-id: k2m5jlwoi-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2m5jlwoi-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
